name: Deploy
on:
  push:
    branches: "main"
jobs:
  deploy_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/csdsinc
            git pull
            npm install
            npm run build
            pm2 restart 0
